openapi: 3.0.3
info:
  title: Jira Integration API
  description: API for integrating with Jira
  version: 1.0.0

servers:
  - url: /api
    description: Backend proxy server

paths:
  /jira/issues:
    post:
      summary: Fetch Jira issues
      description: Retrieve issues from Jira project
      operationId: fetchJiraIssues
      tags:
        - Jira
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JiraApiConfig'
      responses:
        '200':
          description: Successfully retrieved issues
          content:
            application/json:
              schema:
                type: object
                properties:
                  issues:
                    type: array
                    items:
                      $ref: '#/components/schemas/JiraIssue'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    JiraApiConfig:
      type: object
      required:
        - domain
        - token
        - projectKey
        - email
      properties:
        domain:
          type: string
          description: Jira domain
          example: jira-freee.atlassian.net
        token:
          type: string
          description: API token for authentication
        projectKey:
          type: string
          description: Jira project key
          example: KNOQ
        email:
          type: string
          description: Email address for Basic authentication
          example: user@example.com
        apiVersion:
          type: string
          description: Jira REST API version
          default: '3'
          example: '3'

    JiraIssue:
      type: object
      required:
        - id
        - key
        - summary
        - status
        - priority
        - created
        - updated
      properties:
        id:
          type: string
          description: Issue ID
        key:
          type: string
          description: Issue key
          example: KNOQ-123
        summary:
          type: string
          description: Issue summary
        status:
          type: string
          description: Current status
          example: In Progress
        priority:
          type: string
          description: Issue priority
          example: High
        assignee:
          type: string
          description: Assigned user's display name
          nullable: true
        created:
          type: string
          format: date-time
          description: Creation timestamp
        updated:
          type: string
          format: date-time
          description: Last update timestamp

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
        errorMessages:
          type: array
          items:
            type: string
          description: Detailed error messages